# Предназначается для импорта из родительской директории
from checks.anchors import anchors
from checks.callback import callback
from checks.contacts import contacts
from checks.fbpixel import fbpixel
from checks.forms_action import forms_action
from checks.forms_get import forms_get
from checks.forms_post import forms_post
from checks.info import info
from checks.input_email import input_email
from checks.inputs_exist import inputs_exist
from checks.inputs_nonrequired import inputs_nonrequired
from checks.inputs_required import inputs_required
from checks.is_land import is_land
from checks.lang_confirm import lang_confirm
from checks.lang_elements import lang_elements
from checks.lang_main import lang_main
from checks.lang_meta import lang_meta
from checks.lead import lead
from checks.lead_check import lead_check
from checks.page_exist import page_exist
from checks.phone_code import phone_code
from checks.policy_blank import policy_blank
from checks.policy_exist import policy_exist
from checks.policy_lang import policy_lang
from checks.policy_link import policy_link
from checks.postback import postback
from checks.pre_links import pre_links
from checks.result import result
from checks.shipping_post import shipping_post
from checks.submit import submit
from checks.title import title
from checks.wf_frame import wf_frame